# Generated by Django 5.2.2 on 2025-06-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_merge_20250614_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('food', 'Food'), ('furniture', 'Furniture'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
