# Generated by Django 5.2.2 on 2025-06-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='guest_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
